name = "hf-keepalive"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

# 创建后，把 `wrangler kv namespace create KV` 返回的 id 填到这里
[[kv_namespaces]]
binding = "KV"
id = "01501527dc7a4f5c91ea73325c0a805e"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
ADMIN_PASSWORD = "boyu123456789"
SESSION_SECRET = "dd1c20ecb69348d583b58942665d4d0b"


# 通过 wrangler secret put 设置：
#   ADMIN_PASSWORD    登录密码
#   SESSION_SECRET    HMAC 签名密钥（建议 openssl rand -base64 32）
